// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tiktokdb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Aweme struct {
	_tab flatbuffers.Table
}

func GetRootAsAweme(buf []byte, offset flatbuffers.UOffsetT) *Aweme {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Aweme{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAweme(buf []byte, offset flatbuffers.UOffsetT) *Aweme {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Aweme{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Aweme) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Aweme) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Aweme) ShareLink() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AwemeStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AwemeAddShareLink(builder *flatbuffers.Builder, shareLink flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(shareLink), 0)
}
func AwemeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
