// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tiktokdb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserAwemes struct {
	_tab flatbuffers.Table
}

func GetRootAsUserAwemes(buf []byte, offset flatbuffers.UOffsetT) *UserAwemes {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserAwemes{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserAwemes(buf []byte, offset flatbuffers.UOffsetT) *UserAwemes {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserAwemes{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserAwemes) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserAwemes) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserAwemes) AwemeIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *UserAwemes) AwemeIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func UserAwemesStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserAwemesAddAwemeIds(builder *flatbuffers.Builder, awemeIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(awemeIds), 0)
}
func UserAwemesStartAwemeIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func UserAwemesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
