// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tiktokdb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TikTokUser struct {
	_tab flatbuffers.Table
}

func GetRootAsTikTokUser(buf []byte, offset flatbuffers.UOffsetT) *TikTokUser {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TikTokUser{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTikTokUser(buf []byte, offset flatbuffers.UOffsetT) *TikTokUser {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TikTokUser{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TikTokUser) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TikTokUser) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TikTokUser) LatestUsername() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TikTokUser) LastUsedMincursor() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TikTokUser) Tiktoks(obj *TikTok, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TikTokUser) TiktoksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TikTokUserStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TikTokUserAddLatestUsername(builder *flatbuffers.Builder, latestUsername flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(latestUsername), 0)
}
func TikTokUserAddLastUsedMincursor(builder *flatbuffers.Builder, lastUsedMincursor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(lastUsedMincursor), 0)
}
func TikTokUserAddTiktoks(builder *flatbuffers.Builder, tiktoks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(tiktoks), 0)
}
func TikTokUserStartTiktoksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TikTokUserEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
