// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tiktokdb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TikTok struct {
	_tab flatbuffers.Table
}

func GetRootAsTikTok(buf []byte, offset flatbuffers.UOffsetT) *TikTok {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TikTok{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTikTok(buf []byte, offset flatbuffers.UOffsetT) *TikTok {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TikTok{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TikTok) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TikTok) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TikTok) Awemeid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TikTok) ShareLink() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TikTokStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TikTokAddAwemeid(builder *flatbuffers.Builder, awemeid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(awemeid), 0)
}
func TikTokAddShareLink(builder *flatbuffers.Builder, shareLink flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(shareLink), 0)
}
func TikTokEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
